name: Examples

on: [push]

jobs:
  render_jsonnet_to_stdout:
    runs-on: ubuntu-latest
    name: Print rendered result to STDOUT
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
          params: 'test=true,env=stag'
  render_jsonnet_to_single_file:
    runs-on: ubuntu-latest
    name: Write rendered result to file
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
          output_file: test/output.json
      - name: Validation
        run: diff test/output.json test/expected-example.json
  render_jsonnet_to_multiple_files:
    runs-on: ubuntu-latest
    name: Write rendered result to multiple output files
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Jsonnet
        uses: ./
        id: jsonnet
        with:
          file: 'test/example.jsonnet'
          output_dir: test/multi-file-output/
          params: 'test=true dryrun=false;env=prod'
      - name: Validation
        run: diff test/multi-file-output/person1 test/person1
